################################
# project configuration
################################

# C++ project
language: cpp
dist: xenial
sudo: false

################################
# build matrix
################################

matrix:
  include:

  # Windows
  # MSVC 2017 32-bit
  - os: windows
    env: CMAKE_CONFIGURE_OPTIONS="-A Win32" CMAKE_BUILD_OPTIONS="--config Release" CTEST_OPTIONS="-C Release"

  # MSVC 2017 64-bit
  - os: windows
    env: CMAKE_CONFIGURE_OPTIONS="-A x64" CMAKE_BUILD_OPTIONS="--config Release" CTEST_OPTIONS="-C Release"

  # macOS
  # Xcode 10.1 (Clang 6)
  - os: osx
    env: CMAKE_CONFIGURE_OPTIONS="-DCMAKE_BUILD_TYPE=Release" CMAKE_BUILD_OPTIONS="" CTEST_OPTIONS="-C Release"
    osx_image: xcode10.1

  # Linux
  # gcc 7
  - os: linux
    env: CMAKE_CONFIGURE_OPTIONS="-DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_BUILD_TYPE=Release" CMAKE_BUILD_OPTIONS="" CTEST_OPTIONS="-C Release"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
            key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial-rc main'
        packages:
          - gcc-7
          - g++-7
          - xorg-dev
          - libgl1-mesa-dev
          - cmake
    before_script:
      # A hardcoded version of CMake is earlier in the PATH than cmake installed by apt,
      # so we remove it fully here.
      - sudo rm -rf /usr/local/cmake-3.12.4

  # clang 6
  - os: linux
    env: CMAKE_CONFIGURE_OPTIONS="-DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DCMAKE_BUILD_TYPE=Release" CMAKE_BUILD_OPTIONS="" CTEST_OPTIONS="-C Release"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-xenial-6.0
          - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
            key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial-rc main'
        packages:
          - gcc-7
          - g++-7
          - clang-6.0
          - xorg-dev
          - libgl1-mesa-dev
          - cmake
    before_script:
      # A hardcoded version of CMake is earlier in the PATH than cmake installed by apt,
      # so we remove it fully here.
      - sudo rm -rf /usr/local/cmake-3.12.4

################################
# build script
################################

script:
  - mkdir build && cd build
  - cmake ${CMAKE_CONFIGURE_OPTIONS} ..
  - cmake --build . ${CMAKE_BUILD_OPTIONS}
  - ctest ${CTEST_OPTIONS}

notifications:
  email: false
