################################
# project configuration
################################

# C++ project
language: cpp
dist: xenial
sudo: false

################################
# build matrix
################################

matrix:
  include:

  # Windows
  # MSVC 2017 32-bit
  - os: windows
    env: CMAKE_CONFIGURE_OPTIONS="-A Win32" CMAKE_BUILD_OPTIONS="--config Release" CTEST_OPTIONS="-C Release"

  # MSVC 2017 64-bit
  - os: windows
    env: CMAKE_CONFIGURE_OPTIONS="-A x64" CMAKE_BUILD_OPTIONS="--config Release" CTEST_OPTIONS="-C Release"

  # macOS
  # Xcode 10.1 (Clang 6)
  - os: osx
    env: CMAKE_CONFIGURE_OPTIONS="-DCMAKE_BUILD_TYPE=Release" CMAKE_BUILD_OPTIONS="" CTEST_OPTIONS="-C Release"
    osx_image: xcode10.1

  # Linux
  # gcc 7
  - os: linux
    env: CMAKE_CONFIGURE_OPTIONS="-DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_BUILD_TYPE=Release" CMAKE_BUILD_OPTIONS="" CTEST_OPTIONS="-C Release"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
          - xorg-dev
          - libgl1-mesa-dev

  # clang 6
  - os: linux
    env: CMAKE_CONFIGURE_OPTIONS="-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release" CMAKE_BUILD_OPTIONS="" CTEST_OPTIONS="-C Release"
    addons:
      apt:
        sources:
          - llvm-toolchain-xenial-6.0
        packages:
          - clang-6.0
          - xorg-dev
          - libgl1-mesa-dev

################################
# build script
################################

script:
  - mkdir build && cd build
  - cmake ${CMAKE_CONFIGURE_OPTIONS} ..
  - cmake --build . ${CMAKE_BUILD_OPTIONS}
  - ctest ${CTEST_OPTIONS}

notifications:
  email: false
